# Generated by Django 5.2.6 on 2025-09-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_service_api', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('SOFT', 'SOFT'), ('HARD', 'HARD')], default='SOFT', max_length=10),
        ),
    ]
