# Generated by Django 5.2.6 on 2025-09-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_service_api', '0004_alter_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['-borrow_date']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id']},
        ),
    ]
